pages:
  image: alpine:latest
  stage: deploy
  script:
    - mkdir public/
    - cp -r es public/
    - cp -r images public/
    - cp index.html public
  artifacts:
    paths:
      - public
  only:
    - main