pages:
  image: alpine:latest
  stage: deploy
  script:
    - mkdir public/
    - cp -r es/* public/es
    - cp -r images/* public/images
    - cp index.html public
  artifacts:
    paths:
      - public
  only:
    - main